# Generated by Django 3.0.7 on 2020-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20200606_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dia_locacao',
            field=models.DateField(null=True),
        ),
    ]
